version: '3'

services:
  terraform:
    hostname: terraform
    environment:
      AWS_ACCESS_KEY_ID: ${TERRAFORM_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${TERRAFORM_AWS_SECRET_ACCESS_KEY}
    build:
      context: '.'
    volumes:
    - ".:/srv/app"
    command: "tail -f /dev/null"
